name: donet-stackspot-mongoprovider-plugin
description: Provedor de acesso ao bando NoSql mongoDb
display-name: donet-stackspot-mongoprovider-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - dotnet 7
  - dotnet 6
  - dotnet 5
  - dotnet core 3.1
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "C#"
  - ".Net"
types:
  - app
inputs:
  - label: String de conexão
    type: text
    name: string_conexao

  - label: Nome do banco de dados
    type: text
    name: nome_banco_dados

  - label: Selecione o tipo da instalação do plugin
    type: text
    name: type_mongo_plugin_import
    items:
      - "dll-reference"      
      - "nuget"

computed-inputs:
  path_plugin_project: '{{component_path | replace("\\","\/")}}/templates/src' ##Plugin path to build befere use it.
  base_path: "{% if global_computed_inputs.src_base_path is defined and global_computed_inputs.src_base_path != '' %}{{global_computed_inputs.src_base_path}}{% else %}{{'.'}}{% endif %}"
  path_infrastructure: ""

hooks:
  - type: run-script
    trigger: before-render
    script: scripts/folder-validation.py
  #building plugin project
  - type: run
    trigger: before-render
    windows:
      - dotnet restore {{computed_inputs.path_plugin_project}}
      - dotnet build {{computed_inputs.path_plugin_project}} -o {{computed_inputs.path_plugin_project}}/output -c Release
  #Plugin build and reference Dll
  - type: run-script
    trigger: before-render
    script: scripts/create-folder-libs.py
    condition:
      variable: type_mongo_plugin_import
      operator: ==
      value: dll-reference
  - type: edit
    trigger: before-render
    path: "{{global_inputs.project_name}}/{{global_inputs.project_name}}.csproj"
    changes:
      - search:
          string: "</ItemGroup>"
          insert-after:
            snippet: snippets/mongo-providers.txt
          when:
            not-exists: "NOT-RENDER"
  #clean template file copy
  - type: run-script
    trigger: after-render
    script: scripts/remove-folder.py
  #configuração startup
  - type: edit
    trigger: before-render
    path: "{{global_inputs.project_name}}/Program.cs"
    changes:
      - search:
          string: "using"
          insert-before:
            value: "using MongoProvider;\n"
          when:
            not-exists: "using MongoProvider;"
      - search:
          string: "var app = builder.Build();"
          insert-before:
            value: "builder.Services.AddMongoProviders(builder.Configuration);\n"
          when:
            not-exists: "builder.Services.AddMongoProviders(builder.Configuration);"
  #appsetting
  - type: edit
    trigger: before-render
    path: "{{global_inputs.project_name}}/appsettings.json"
    changes:
      - search:
          string: "},"
          insert-after:
            snippet: snippets/mongo.txt
          when:
            not-exists: "\"Mongo\""
  #format the code
  - type: run
    trigger: after-render    
    commands:
      - dotnet dotnet-format -f {{global_inputs.project_name}}  --include-generated
