name: ci

on:
  push:
    tags:
      - v*
    branches: [main]
  pull_request:
    branches: [main, feature/*]

jobs:
  build:
    env:
      src: "./templates/src/"      
      PROJECT_SLN: "./templates/src/ScaffoldDotnet.MongoProvider.sln"
      PROJECT_BIN3_1: "./templates/src/ScaffoldDotnet.MongoProvider/bin/Release/netcoreapp3.1"
      PROJECT_BIN5: "./templates/src/ScaffoldDotnet.MongoProvider/bin/Release/net5.0"
      PROJECT_BIN6: "./templates/src/ScaffoldDotnet.MongoProvider/bin/Release/net6.0"
      PROJECT_BIN7: "./templates/src/ScaffoldDotnet.MongoProvider/bin/Release/net7.0"

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["7.0.100"]

    steps:
      - uses: actions/checkout@v2

      - name: Get Build Version 🏷️
        run: |
          Import-Module .\scripts\GetBuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: Setup NuGet 🔧
        uses: NuGet/setup-nuget@v1.0.5

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }} 🔧
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Clean Dependencies 📦
        run: dotnet clean ${{env.PROJECT_SLN }}

      - name: Restore Dependencies 📦
        run: dotnet restore ${{env.PROJECT_SLN }}

      - name: Build ⚙️
        run: dotnet build ${{env.PROJECT_SLN }} -c Release -p:Version=$BUILD_VERSION --no-restore

      - name: Run Infer .Net 3.1 🔍
        uses: microsoft/infersharpaction@v1.2
        with:
          binary-path: ${{ env.PROJECT_BIN3_1 }}

      - name: Run Infer .Net 5.0 🔍
        uses: microsoft/infersharpaction@v1.2
        with:
          binary-path: ${{ env.PROJECT_BIN5 }}

      - name: Run Infer .Net 6.0 🔍
        uses: microsoft/infersharpaction@v1.2
        with:
          binary-path: ${{ env.PROJECT_BIN6 }}

      - name: Run Infer .Net 7.0 🔍
        uses: microsoft/infersharpaction@v1.2
        with:
          binary-path: ${{ env.PROJECT_BIN7 }}

      - name: Publish Package ✉️
        if: startsWith(github.ref, 'refs/tags/v')
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_TOKEN}}
